#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]
ORDER=['core.yaml','evidence.yaml','verse.yaml','architecture.yaml','multiplayer.yaml','ui.yaml','provenance.yaml','modes.yaml','output_contract.yaml']

def load_sections():
    out=[]
    for name in ORDER:
        p=ROOT/'prompt_sources'/name
        data=json.loads(p.read_text(encoding='utf-8'))
        out.append((data['title'],data['lines']))
    return out

def body(language='en', with_ui=False):
    lines=[]
    if language=='fr':
        lines += ['Tu vas utiliser le dépôt Verse AI Knowledge comme source principale pour Verse / UEFN.','Repository: https://github.com/ariyo-code/Verse-AI-Knowledge','']
    else:
        lines += ['Use Verse AI Knowledge as the primary repository source for Verse / UEFN.','Repository: https://github.com/ariyo-code/Verse-AI-Knowledge','']
    for title,items in load_sections():
        if title=='UI' and not with_ui:
            continue
        lines.append(f'## {title}')
        lines += [f'- {x}' for x in items]
        lines.append('')
    lines += ['=== USER TASK ===','', '[ÉCRIS ICI TA DEMANDE / WRITE YOUR TASK HERE]','']
    return '\n'.join(lines)

def render_public():
    return '# Verse AI Knowledge — Current Chat Prompt\n\nGenerated from `prompt_sources/`. Do not edit this file directly.\n\n## Français\n\n```text\n'+body('fr',True)+'```\n\n## English\n\n```text\n'+body('en',True)+'```\n'

def build():
    targets={
      ROOT/'PROMPT_AI_CHAT_FR_EN.md':render_public(),
      ROOT/'portable/current/VERSE_AI_MASTER_PROMPT.txt':body('en',False),
      ROOT/'portable/current/VERSE_AI_MASTER_PROMPT_WITH_UI.txt':body('en',True),
      ROOT/'portable/current/TASK_TEMPLATE.txt':'=== USER TASK ===\n\n[WRITE TASK HERE]\n',
    }
    for p,text in targets.items():
        p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8')
    return targets

if __name__=='__main__':
    for p in build(): print(p.relative_to(ROOT))
